# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: intelligence-project
 #Note: A namespace with many characters will cause storage  account creation to fail due to storage account names having a limit of 24 characters.
  location: westus2

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: $(namespace)
  aml_workspace: $(namespace)
  application_insights: $(namespace)
  key_vault: $(namespace)
  container_registry: $(namespace)
  storage_account: $(namespace)

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: $(namespace)
  terraform_st_location: $(location)
  terraform_st_storage_account: $(namespace)
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
