$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: sms-spam-sms-spam-online
model: azureml:sms-spam-model@latest
instance_type: Standard_DS2_v2
instance_count: 1
